---
email: javier.sanchez.rois@gmail.com
baseurl: ''
paginate: 5
paginate_path: /blog/page-:num
google_analytics: 
title: Detached Head
description: 
url: ''
twitter_username: jsrois
default_img: 
name: Javi
profile_img: /assets/images/perfil
profile: This is Javi. He likes software and stuff. He though it was a good idea to
  write this. Don't be too hard on him. He has a weak psyche.
social:
  github: https://github.com/jsrois
  twitter: https://twitter.com/jsrois
exclude:
- _screenshots
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
markdown: kramdown
permalink: /:year/:month/:day/:title/
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
