---
email: javier.sanchez.rois@gmail.com
baseurl: ''
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 
title: 
description: 
url: ''
twitter_username: jsrois
default_img: 
name: Javi
profile_img: 
profile: 
social:
  github: jsrois
  twitter: jsrois
exclude:
- _screenshots
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
